### ISSUE TITLE
Sudo is required for Vagrant shell provisioning

### ISSUE THREAD

**Issue by arky** [vladimir-babichev/vagrant-openwrt-box#3]
Trying to provision using [inline shell scripts](https://www.vagrantup.com/docs/provisioning/shell.html) tend to fail with SSH error:

```shell
$ vagrant  provision 
==> default: Running provisioner: shell...
    default: Running: inline script
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
Debugging further I see that this might be due to missing sudo on openwrt ?

```shell
DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: Execute: chown -R root /tmp/vagrant-shell (sudo=true)
DEBUG ssh: stderr: ash: 
DEBUG ssh: stderr: sudo: not found
DEBUG ssh: stderr: 
```

Perhaps adding 'opkg install sudo' in packer build should resolve this problem?

**Comment by arky** [comment]
@vladimir-babichev Did a quick test. I added 'ssh' package in the guest and then ran provisioning. This time it works. So the solution is to include 'sudo' package in the packer build.

```shell 
root@OpenWrt:~# opkg install sudo
Installing sudo (1.8.28p1-1) to root...
Downloading http://downloads.openwrt.org/releases/19.07.3/packages/x86_64/packages/sudo_1.8.28p1-1_x86_64.ipk
Configuring sudo.
root@OpenWrt:~# which sudo
/usr/bin/sudo
root@OpenWrt:~# exit
Connection to 127.0.0.1 closed.

$ vagrant  provision 
==> default: Running provisioner: shell...
    default: Running: inline script
```

**Comment by arky** [comment]
@vladimir-babichev Closing this bug and up-streaming this bug https://github.com/hashicorp/vagrant/issues/11790 Thanks!

**Comment by vladimir-babichev** [comment]
Hey @arky, 

Thanks for raising an issue with Hashicorp, hope they address it soon.

Coming back to your question, you don't really need `sudo` for inline shell provisioner to work. Taking to account that default vagrant user is `root` you need  to add `privileged: false` to your shell provisioner configuration in `Vagrant` file:
```ruby
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    opkg update
  SHELL
```

I'll update `README.md` to include this issue.
