### ISSUE TITLE
image for 22.03

### ISSUE THREAD

**Issue by lelutin** [vladimir-babichev/vagrant-openwrt-box#7]
Hi there, this project is pretty cool - I'm using to run tests for my ansible playbooks for openwrt hosts. thanks for maintaining this (and thanks for building in libvirt/qemu support) !

I can build my own box for 22.03 since there's a version variable in the makefile, but I was wondering if you were willing to publish an image on app.vagrantup.com with that version since it's now the most current openwrt release?

cheers!

**Comment by vladimir-babichev** [comment]
Glad you find it useful! I've build and published [22.03 image](https://app.vagrantup.com/vladimir-babichev/boxes/openwrt-22.03) @ Vagrant Cloud.

Is any of your OpenWrt Ansible Playbooks available publicly by any chance? Planning to do a bit of home automation during Chirstmas hols 😀

**Comment by lelutin** [comment]
wow nice thanks for the new box version! that was quick :)

I haven't really started implementing things in detail yet. I'm also automating my home setup so it'll be super simple -- I'm mostly interested in removing the need for backups of those devices and also to make it easier to reinstall the packages after a major upgrade.

but I can make a sign when I have something. I was planning to use https://github.com/gekmihesg/ansible-openwrt as a base for the provisioning. I can see that's also what you used in your example repository.

Cheers!

**Comment by vladimir-babichev** [comment]
Sounds great. Was happy to help.
